# Dockerfile for building the wavefront go-proxy .deb and .rpm packages.
FROM golang:1.9.2
RUN apt-get -qq update
RUN apt-get -qq install -y --no-install-recommends ruby ruby-dev rubygems build-essential rpm
RUN gem install fpm --version 1.9.3

ENV USER wavefronthq
ENV REPO go-proxy

RUN mkdir -p $GOPATH/src/github.com/$USER
COPY . $GOPATH/src/github.com/$USER/$REPO
RUN cd $GOPATH/src/github.com/$USER/$REPO && make package
